### ISSUE TITLE
Is there any documentation how to use rules.js, what benefit it provides ?

### ISSUE THREAD

**Issue by jitendravyas** [whmountains/gulp-atomizer#11]
I understood how to use config and what is the benefit of it but I don't yet understand the value of rules.

**Comment by jitendravyas** [comment]
you have mentioned

```
// A hook for another undocumented feature of atomizer.  
      // You can use it to create custom ACSS 'functions'.
      // Calls `acss.addRules(options.addRules)` under the hood.
      // See the tests for an example of how to use this.
      addRules: require('./rules.js')
```

But I don't see any rules.js file in test folder

**Comment by whmountains** [comment]
It's used to create custom helper functions.  For example, `flexBox(column)` could translate into `D(f) Fd(c)`.  That's not a very useful example, but you get the idea.  You can make a whole package of acss classes, some of which may take arguments from the parent function.

I haven't used it, so I don't know the syntax.  @AbsentSemicolon sent me a pull request a while back adding the functionality, so I merged it.  Sorry I can't help more.  Maybe he will jump in and explain.

In the mean time, here is an example rules.js:
```
module.exports = [
  {
    'type': 'helper',
    'id': 'test-helper',
    'name': 'Test Helper',
    'matcher': 'test-helper',
    'noParams': true,
    'styles': {
      'cursor': 'pointer'
    }
  },
  {
    'type': 'pattern',
    'id': 'test-pattern',
    'name': 'Test Pattern',
    'matcher': 'TestPattern',
    'allowParamToValue': false,
    'styles': {
      'background-repeat': '$0'
    },
    'arguments': [{
      'n': 'no-repeat'
    }]
  }
]
```
And here is a snippet of HTML that uses it
```
<div class="TestPattern(n) test-helper"></div>
```
And finally the resulting ACSS:
```
.test-helper {
  cursor: pointer;
}
.TestPattern\(n\) {
  background-repeat: no-repeat;
}
```

**Comment by whmountains** [comment]
> But I don't see any rules.js file in test folder

I have it inline in the test.js file.  What I just posted is taken directly from the unit tests.  I'll pull it into a separate file to avoid confusing anyone else in the future.
