### ISSUE TITLE
Do you know why and when we will need namespace: '#somename'  ?

### ISSUE THREAD

**Issue by jitendravyas** [whmountains/gulp-atomizer#12]
This part

```
      // Custom css generation options to pass to atomizer's `getCSS` function.
      // This is an undocumented feature of atomizer, so I don't test for it.
      cssOptions: {
        namespace: '#atomic'
      },
```

**Comment by whmountains** [comment]
Yes.  That's in case you want your ACSS to be scoped to only one section of your site.  Normally, if you have `<h1 class="C(red)">` ACSS will create this rule: `.C(red) { color: red; }`.

With `namespace: '#atomic'` it will instead create `#atomic .C(red) { color: red; }`.  That way you can scope your ACSS to a certain part of a page to prevent conflicts.  Honestly I think it's pretty rare that you would need to worry about conflicts though.

**Comment by whmountains** [comment]
I just looked at a slide deck from @thierryk and realized I probably gave you the wrong reason.

The more common reason for using a namespace is to give your ACSS rules a higher specificity.  If your Atomic CSS coexists with other CSS, your ACSS rules can get stomped on by more specific rules.  Usually the behavior you want is the other way around.  Using an id for a namespace allows you to give you more specificity to win the selector war.

**Comment by thierryk** [comment]
@whmountains is right, that's the reason we use a namespace. 

Even though most people use `!important` to make sure styles related to their utility classes don't get overwritten, we thought it was *better* to go with a `id` to bump their specificity while allowing styling via JavaScript (inline styles).

Note that if you cannot access the markup to set that `id` on a top ancestor (i.e. `html` or `body`), and if you target browsers that support the `:not()` selector then you can simply use whatever you want as that `id` does not have to be present in the markup but still valid to bump the specificity of those rules (`0,1,1,0`). 
For example, you'd get this: 

```
:not(#foo) .C\(teal\) {
  color: teal;
} 
```
