### ISSUE TITLE
Followed your example but getting Cannot find module 'acss-config.js'

### ISSUE THREAD

**Issue by jitendravyas** [whmountains/gulp-atomizer#9]
my gulpfile

```
var gulp = require('gulp');
var acss = require('gulp-atomizer');
var acssConf = require('acss-config.js');


gulp.task('acss', function() {
  return gulp.src('./*.html')
  .pipe(acss('_atoms.scss', acssConf, {
    namespace: '#atomic'
  }))
    .pipe(gulp.dest('dist'));
});

```

**Comment by whmountains** [comment]
You have to create acss-config.js before you can require it.  This is no different than how it would be if you were using atomizer directly.

**Comment by whmountains** [comment]
Your question inspired me to clean up the API though, and I actually just published a new major version.

Instead of accepting different options as a series of arguments, we now accept them as properties of a single configuration object.  Check out the new README and tell me if it makes any more sense.

**Comment by jitendravyas** [comment]
I already have `acss-config.js`

**Comment by whmountains** [comment]
Aaah.  Mistake in my example then.  It should be `require('./acss-config.js')` and not require('acss-config.js')`.  I'll get that fixed.

**Comment by jitendravyas** [comment]
I get error with `./acss-config.js`

**Comment by whmountains** [comment]
same error?

**Comment by jitendravyas** [comment]
This is an error example of on of them

![gulpfile js my-projects atomizer-gulp pde4e](https://cloud.githubusercontent.com/assets/77309/20645176/717b2346-b47b-11e6-940a-22584c01e024.jpg)

**Comment by whmountains** [comment]
What happens if you change line 36 to `acssConfig: require('./acssConf.js'),`?  Or did you already do that?

**Comment by jitendravyas** [comment]
This is with `./`

![-zsh 1 402jy](https://cloud.githubusercontent.com/assets/77309/20645181/abc128b6-b47b-11e6-95ad-e6ac171a4d60.jpg)

**Comment by whmountains** [comment]
Okay, that's clearly a problem.  I can see what's wrong in the code and I've got it fixed but I'm working on expanding the unit tests before I push the fix.  Should be done in an hour or so.

**Comment by whmountains** [comment]
It's fixed.  Both examples on the homepage now work fine for me.  Does the latest version work for you now?

**Comment by jitendravyas** [comment]
How do you update the plugin?
Do you have any code in your `acssConf.js`?

My Gulp version
CLI version 1.2.1
Local version 3.9.1

Node Version
6.7.0

**Comment by whmountains** [comment]
To update, you run `npm upgrade gulp-atomizer`

No, you don't need any code in it, but it's where you would put your configuration if you have any.  It's not a JSON file, it's javascript so if you put configuration you have to export it like this:
```javascript
module.exports = {
  // configuration goes here
}
```

**Comment by jitendravyas** [comment]
It's working now. Thanks. I was running wrong command to upgrade.

**Comment by whmountains** [comment]
Great!

BTW I'm curious, are you just going through and testing everything, or do you have a specific project you're working on?  Either way the bug reports are much appreciated.

**Comment by jitendravyas** [comment]
I'm just making an example of how to use Atomizer with Gulp and use its other features like config and rules so I can share it with other people if they ask. 
I wish to use it in a project in future.

**Comment by whmountains** [comment]
Great!  Feel free to PM me on Gitter if you have any questions.  (Github issues work too.)
